# Generated by Django 4.2.3 on 2024-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_movie_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/sampleImg.jpg', upload_to='Images'),
        ),
    ]
